apiVersion: apps/v1
kind: Deployment

metadata:
  name: social-service
  namespace: revhive

spec:
  replicas: 1

  selector:
    matchLabels:
      app: social-service

  template:
    metadata:
      labels:
        app: social-service

    spec:
      containers:
        - name: social-service
          image: tanushreenik/social-service:latest

          ports:
            - containerPort: 8084

          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/revhive_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: sourav
            - name: SPRING_DATASOURCE_PASSWORD
              value: sourav@123
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-registry:8761/eureka

